#-------------------------------
# Site Settings
title: The Mouse Team
logo: '/images/logo.png'
author: Unknown
description: The Mouse Team.


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Contact'
      url: '/contact/'
    - title: 'Elements'
      url: '/elements/'
    - title: 'Mouse Originals'
      url: '/originals/'


#-------------------------------
# Hero Settings
hero:
  hero__title: Changing The World, One App At A Time.
  hero__description: (Not just another software team). We are a team of Android developers. We create our own original apps, used and loved by thousands all around the world. We also serve our clients and bring their app ideas to life. We are the Mouse Team !!
  
#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Portfolio
  portfolio__gallery:
    - image:/images/eleftheria.png
      title: SeriesMe
      description: <a href="/seriesme/">SeriesMe</a>

    - image: /images/hara.png
      title: Paula Vermeulen
      description: Gray mountain covered by mountain <a href="https://unsplash.com/photos/_f2m3mEkaaU">Unsplash</a>

    - image: /images/roadai.png
      title: Bench Accounting
      description: White wooden table near brown chair <a href="https://unsplash.com/photos/nvzvOPQW0gc">Unsplash</a>

    - image: /images/upliftme.png
      title: Nord Wood
      description: White ceramic mug <a href="https://unsplash.com/photos/nDd3dIkkOLo">Unsplash</a>

    - image: /images/hashme.png
      title: Luca Bravo
      description: White ribs in a facade against a white sky <a href="https://unsplash.com/photos/alS7ewQ41M8">Unsplash</a>

    - image: /images/budgetme.png
      title: Isaac Benhesed
      description: Minimalist black coffee <a href="https://unsplash.com/photos/onLbXleIkds">Unsplash</a>

    - image: /images/noteme.png
      title: Water Journal
      description: Water Journal is a bi-annual publication exploring the beauty and complexity of all things water <a href="https://unsplash.com/photos/EbuaKnSm8Zw">Unsplash</a>

    - image: /images/schoolpool.png
      title: Luca Bravo
      description: Worms eye view of city buildings <a href="https://unsplash.com/photos/a6x7YPiNxwI">Unsplash</a>

#-------------------------------
# Footer Settings
social:
- {icon: "ion-logo-twitter", color: "#55acee", label: Twitter, link: "https://twitter.com"}
- {icon: "ion-logo-linkedin", color: "#3b5999", label: Facebook, link: "https://facebook.com"}
- {icon: "ion-logo-instagram", color: "#bd081c", label: Pinterest, link: "https://pinterest.com"}
- {icon: "ion-logo-youtube", color: "#ea4c89", label: Dribbble, link: "https://dribbble.com"}


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.
